/* Charts for the canaireview landing page.
 * Data is hard-coded here for now; later this can be replaced by a fetch
 * from a JSON file regenerated by the snapshot pipeline.
 *
 * Release dates below are approximate placeholders (within the user-stated
 * Nov 2025 -- Apr 2026 window). Update them with exact dates when known.
 */

// ---------- Data ----------
// L1 distance: pooled human histogram vs pooled model histogram
//   computed from output/tables/paper_metrics.csv
// Correlation: per-paper Pearson r between model score and mean human score
//   (also from output/tables/paper_metrics.csv, "per_paper_Pearson")

const MODEL_DATA = {
  opus: [
    { name: "Opus 4.5", date: "2025-11-04", l1: 0.814, corr: 0.234 },
    { name: "Opus 4.6", date: "2026-01-15", l1: 0.650, corr: 0.267 },
    { name: "Opus 4.7", date: "2026-04-08", l1: 0.454, corr: 0.310 },
  ],
  gpt: [
    { name: "GPT-5.1", date: "2025-11-20", l1: 0.898, corr: 0.133 },
    { name: "GPT-5.4", date: "2026-02-10", l1: 0.734, corr: 0.208 },
    { name: "GPT-5.5", date: "2026-04-22", l1: 0.449, corr: 0.235 },
  ],
};

const COLORS = {
  opus: "#c2410c", // burnt orange (Anthropic-leaning)
  gpt:  "#1e3a8a", // navy (OpenAI-leaning)
};

// ---------- Plugin registration ----------
if (window["chartjs-plugin-annotation"]) {
  Chart.register(window["chartjs-plugin-annotation"]);
}

// Sane default fonts for chart text
Chart.defaults.font.family = "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif";
Chart.defaults.font.size = 12;
Chart.defaults.color = "#444";

// ---------- Helpers ----------
function pointsFor(vendor, metric) {
  return MODEL_DATA[vendor].map(m => ({
    x: m.date,
    y: m[metric],
    name: m.name,
  }));
}

function fmtDate(d) {
  // d is a Date or ISO string; format as "Apr 8, 2026"
  const dt = (d instanceof Date) ? d : new Date(d);
  return dt.toLocaleDateString("en-US",
    { year: "numeric", month: "short", day: "numeric" });
}

function buildTooltipCallbacks(metricLabel) {
  return {
    title: (items) => items.length ? items[0].raw.name : "",
    label: (item) => {
      const r = item.raw;
      return `${metricLabel} = ${r.y.toFixed(3)}  (released ${fmtDate(r.x)})`;
    },
  };
}

// Use a wider date window so end-points don't sit on the chart edge
const X_MIN = "2025-10-15";
const X_MAX = "2026-05-15";

const SHARED_X = {
  type: "time",
  min: X_MIN,
  max: X_MAX,
  time: {
    unit: "month",
    displayFormats: { month: "MMM yyyy" },
    tooltipFormat: "MMM d, yyyy",
  },
  title: { display: true, text: "Model release date", padding: 10 },
  grid: { color: "#eee" },
};

// ---------- Figure 1: L1 distance ----------
new Chart(document.getElementById("chart-l1"), {
  type: "line",
  data: {
    datasets: [
      {
        label: "Anthropic Opus",
        data: pointsFor("opus", "l1"),
        borderColor: COLORS.opus,
        backgroundColor: COLORS.opus,
        pointRadius: 5,
        pointHoverRadius: 8,
        pointBorderWidth: 2,
        pointBackgroundColor: "#fff",
        borderWidth: 2.2,
        tension: 0.05,
      },
      {
        label: "OpenAI GPT",
        data: pointsFor("gpt", "l1"),
        borderColor: COLORS.gpt,
        backgroundColor: COLORS.gpt,
        pointRadius: 5,
        pointHoverRadius: 8,
        pointBorderWidth: 2,
        pointBackgroundColor: "#fff",
        borderWidth: 2.2,
        borderDash: [],
        tension: 0.05,
      },
    ],
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
    interaction: { mode: "nearest", intersect: true },
    plugins: {
      legend: {
        position: "top",
        align: "end",
        labels: { usePointStyle: true, padding: 14, boxWidth: 8 },
      },
      tooltip: {
        backgroundColor: "rgba(20,20,20,0.92)",
        padding: 10,
        titleFont: { weight: "600", size: 12 },
        bodyFont: { size: 12 },
        callbacks: buildTooltipCallbacks("L₁"),
      },
      annotation: {
        annotations: {
          zeroLine: {
            type: "line",
            yMin: 0, yMax: 0,
            borderColor: "#666",
            borderWidth: 1,
            borderDash: [4, 4],
            label: {
              display: true,
              content: "exactly the same distribution",
              position: "start",
              backgroundColor: "rgba(255,255,255,0.92)",
              color: "#444",
              font: { size: 10, weight: "500" },
              padding: 4,
              yAdjust: -10,
            },
          },
        },
      },
    },
    scales: {
      x: SHARED_X,
      y: {
        title: { display: true, text: "L₁ distance to human distribution", padding: 10 },
        min: 0,
        max: 1,
        ticks: { stepSize: 0.2 },
        grid: { color: "#eee" },
      },
    },
  },
});

// ---------- Figure 2: Correlation ----------
new Chart(document.getElementById("chart-corr"), {
  type: "line",
  data: {
    datasets: [
      {
        label: "Anthropic Opus",
        data: pointsFor("opus", "corr"),
        borderColor: COLORS.opus,
        backgroundColor: COLORS.opus,
        pointRadius: 5,
        pointHoverRadius: 8,
        pointBorderWidth: 2,
        pointBackgroundColor: "#fff",
        borderWidth: 2.2,
        tension: 0.05,
      },
      {
        label: "OpenAI GPT",
        data: pointsFor("gpt", "corr"),
        borderColor: COLORS.gpt,
        backgroundColor: COLORS.gpt,
        pointRadius: 5,
        pointHoverRadius: 8,
        pointBorderWidth: 2,
        pointBackgroundColor: "#fff",
        borderWidth: 2.2,
        tension: 0.05,
      },
    ],
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
    interaction: { mode: "nearest", intersect: true },
    plugins: {
      legend: {
        position: "top",
        align: "end",
        labels: { usePointStyle: true, padding: 14, boxWidth: 8 },
      },
      tooltip: {
        backgroundColor: "rgba(20,20,20,0.92)",
        padding: 10,
        titleFont: { weight: "600", size: 12 },
        bodyFont: { size: 12 },
        callbacks: buildTooltipCallbacks("r"),
      },
      annotation: {
        annotations: {
          oneLine: {
            type: "line",
            yMin: 1, yMax: 1,
            borderColor: "#666",
            borderWidth: 1,
            borderDash: [4, 4],
            label: {
              display: true,
              content: "complete agreement",
              position: "start",
              backgroundColor: "rgba(255,255,255,0.92)",
              color: "#444",
              font: { size: 10, weight: "500" },
              padding: 4,
              yAdjust: -10,
            },
          },
          zeroLine: {
            type: "line",
            yMin: 0, yMax: 0,
            borderColor: "#666",
            borderWidth: 1,
            borderDash: [4, 4],
            label: {
              display: true,
              content: "completely random",
              position: "start",
              backgroundColor: "rgba(255,255,255,0.92)",
              color: "#444",
              font: { size: 10, weight: "500" },
              padding: 4,
              yAdjust: 10,
            },
          },
        },
      },
    },
    scales: {
      x: SHARED_X,
      y: {
        title: { display: true, text: "Correlation with human scores", padding: 10 },
        min: -0.05,
        max: 1.05,
        ticks: { stepSize: 0.2 },
        grid: { color: "#eee" },
      },
    },
  },
});
